# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CS373 Spring 2016 - Fares Fraij
email: fares@cs.utexas.edu
description: This is a weekly blog to keep track of activities in CS 373 in fall 2015.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fareszf.me" # the base hostname & protocol for your site
twitter_username:
github_username: fareszf

# Build settings
markdown: kramdown

highlighter: rouge
